Timwi/KtaneContent

- HTML/Morse Code translated full (čeština).html
- HTML/Morse Code translated full (עברית).html
- HTML/Morse Code translated full (简体中文).html
- HTML/Password translated full (čeština).html
- HTML/Password translated full (עברית).html
- HTML/Password translated full (简体中文).html
- HTML/The Button translated full (čeština).html
- HTML/The Button translated full (עברית).html
- HTML/The Button translated full (简体中文).html
- HTML/Who’s on First translated full (čeština).html
- HTML/Who’s on First translated full (עברית).html
- HTML/Who’s on First translated full (简体中文).html
Hebrew, Czech, Simplified Chinese
> Translated Modules in 3 more languages

- HTML/Rapid Buttons optimized (NieDzejkob).html
Please tell me if I did it wrong.
> Add an optimized manual for Rapid Buttons

- HTML/The Bulb translated (magyar — A Villanykörte).html
Hungarian translation of "The Bulb" mod's manual in HTML
> Translation

- More/FAQs.html
Added extra facts for "The bus that couldn't slow down" and for "Porcu". Yes, "Porcu" is my legit last name/surname.
> Added extra facts

- HTML/Adjacent Letters translated (Magyar — Szomszédos Betűk).html
- HTML/Adventure Game translated (Magyar - Kalandjáték).html
- HTML/Alphabet translated (Magyar — Ábécé).html
- HTML/Anagrams translated (Magyar  — Anagrammák).html
- HTML/Emoji Math translated (Magyar — Emoji Matek).html
- HTML/Letter Keys translated (magyar — Betűkulcs) .html
- HTML/Piano Keys translated (Magyar — Zongora).html
- HTML/Semaphore translated (Magyar — Szemafor).html
- HTML/Word Scramble translated (Magyar — Kszava).html
List of translated manuals:
Alphabet
Letter Keys
Piano Keys
Semaphore
Adjacent Letters
Adventure Game
Anagrams
Word Scramble
Emoji Math
> Hungarian translations for 9 mods

- HTML/Grocery Store.html
- More/Logfile Analyzer.js
- I made my HTML changes locally instead of in KtaneContent. Though all it does is add red text.
- Logfile Analyzer support no longer calculates. Instead, it just parses already available information to the module listing.
> Include the proper HTML file

- HTML/Planets.html
- Changed steps to make them easier to understand
- Changed references to "black" to "off"
> Planets manual tweaks

- JSON/Flavor Text EX.json
- JSON/Flavor Text.json
- JSON/Mad Memory.json
Updated the JSON files of both Mad Memory and the Flavor Text Modules with...
- New Steam IDs
- New GitHub Links
- Adding my name into the authors (as I have ownership now)
> Update JSONs of Mad Memory & Flavor Text Modules

- HTML/Boot Too Big.html
- HTML/img/Component/Boot Too Big.svg
- JSON/Boot Too Big.json
- Uploaded HTML, PDF and JSON files
> Boot Too Big module upload

- JSON/Factory Maze.json
- JSON/Faulty Digital Root.json
- JSON/Find The Date.json
- JSON/Forget Enigma.json
- JSON/Harmony Sequence.json
- JSON/Skinny Wires.json
- JSON/The Stare.json
Factory Maze, Faulty Digital Root, Find The Date, Forget Enigma, Harmony Sequence, Skinny Wires & The Stare
> TP Score Updates

- HTML/Constellations.html
> Fixed typo on Constellations manual

- JSON/Flower Patch.json
- JSON/Four-Card Monte.json
- Pigpen Rotations reworded (VFlyer)
- Schlag den Bomb optimized (VFlyer)
> Add Following Manuals by VFlyer

- JSON/Left and Right.json
- JSON/Masyu.json
- More/Logfile Analyzer.js
Added A-maze-ing Buttons to LFA
Added tutorial video to Left & Right and Masyu
> LFA and JSON updates

- More/Logfile Analyzer.js
-Added The Very Annoying Button
-Changed Desert Bus logging tag
> LFA updates

- HTML/Forget Me Later.html
Corrects typo for Rule 46 in the manual [and PDF]
> Edit Forget Me Later

- HTML/Accumulation colored (VFlyer).html
- HTML/Micro-Modules reworded (VFlyer).html
- HTML/Simon’s Stages reworded and colored (VFlyer).html
Manuals Edited:
Simon's Stages reworded and colored (VFlyer):
- Change "color" to "colour" in the Terminology section
- Add the word "some" to the ignore section
Manuals Planned to Add:
- Mirco-Modules reworded (VFlyer)
- Accumulation colored (VFlyer)
> Edit+Add Manuals by VFlyer

- HTML/Planets optimized (GeekYiwen).html
Change URL title to specify an optimized version of "Planets" and NOT "Module Name"
> Update Planets optimized (GeekYiwen).html

- HTML/Four-Card Monte optimized (VFlyer).html
- HTML/Four-Card Monte.html
- HTML/Micro-Modules reworded (VFlyer).html
- HTML/Micro-Modules.html
* Update Four-Card Monte.html
Update to match manual from source code
* Add Optimized Manual for Four-Card Monte
* Update Micro-Modules reworded (VFlyer).html
Add section that was used to avoid a (Divide by 0 issue), may throw off other calculations if not edited
* Update Micro-Modules.html
> Modify Kristy's Manuals and Add another manual (#1)

- More/Logfile Analyzer.js
-N&Ms
-The Colored Maze
-The Hyperlink
> Added 3 modules to LFA

- JSON/Intervals.json
> Add intervals SourceUrl

- HTML/Seven Choose Four.html
Contains all the corrections from the previous pull requests, as well as a reformatting to allow the pdf to generate properly.
> Reformatted and corrected Seven Choose Four Manual

- More/Logfile Analyzer.js
-Added Musical Transportation
-Fixed Legendre Symbol
> LFA changes

- JSON/Bone Apple Tea.json
- JSON/Brush Strokes.json
- JSON/Digital Cipher.json
- JSON/Fruits.json
- JSON/Gadgetron Vendor.json
- JSON/Gryphons.json
- JSON/Heraldry.json
- JSON/Simon Scrambles.json
- JSON/Snap!.json
- JSON/Spelling Bee.json
- JSON/The Crafting Table.json
- JSON/The Hangover.json
- JSON/The Matrix.json
- JSON/The Triangle.json
- JSON/Ubermodule.json
- JSON/White Cipher.json
-Bone Apple Tea
-Brush Strokes
-Digital Cipher
-Fruits
-Gadgetron Vendor
-Gryphons
-Heraldry
-Simon Scrambles
-Snap!
-Spelling Bee
-The Crafting Table
-The Hangover
-The Matrix
-The Triangle
-Übermodule
-White Cipher
> Added tutorial videos

- More/Logfile Analyzer.js
> LFA: Group individual rules together in Rainbow Arrows

- HTML/Heraldry optimized (Fang).html
> Heraldry opt error fix Part 2

- HTML/Simon Stores optimized (Fang).html
- JSON/64.json
- JSON/Encrypted Equations.json
- JSON/Kooky Keypad.json
- JSON/The cRule.json
Tutorials are:-
1. 64 by Fartlicker777
2. Encrypted Equations by Fartlicker777
3. The cRule by Procyon
4. Kooky Keypad by Caleb
> Stores Optimized, Tutorial Videos

- HTML/Simon Stores optimized (Fang).html
- JSON/Quiz Buzz.json
Fixed the table where it doesn't show consistently across other browsers
> Stores opt OCD fix

- HTML/Simon Stores optimized (Fang).html
Hopefully this is the last fix
> Stores opt fix (again)

- More/Logfile Analyzer.js
> wrap module icon name in encodeURI

- More/Logfile Analyzer.js
- More/Profile Editor.html
namely, the Profile Editor, and case visualizer in the LFA
> encodeURI in more places where it's relevant

- HTML/14 altered (Fang & Warwick).html
- HTML/Bamboozling Button Grid optimized (Fang).html
- HTML/Bamboozling Button optimized (Fang).html
- HTML/Faulty RGB Maze reworded (Fang).html
- HTML/Forget Perspective optimized (Fang).html
- HTML/Graphic Memory optimized (Fang).html
- HTML/Heraldry optimized (Fang).html
- HTML/Misordered Keys optimized (Fang).html
- HTML/Simon Stores optimized (Fang).html
- HTML/Ultimate Cipher condensed interactive (Fang).html
- HTML/Ultimate Cycle optimized - PDF Version.html
- HTML/UltraStores rearranged (Fang).html
Corrected mistakes that nobody realised when I was starting out
> Corrected Past stupid mistakes

- HTML/Souvenir.html
- JSON/Faulty RGB Maze.json
- JSON/Hereditary Base Notation.json
- JSON/RGB Maze.json
- JSON/Shell Game.json
- JSON/Souvenir.json
- JSON/Transmitted Morse.json
This commit updates the Souvenir metadata to reflect its transfer, and updates the manual and other metadata to reflect newly supported modules.
> Souvenir maintainership transfer and updates

- JSON/Burglar Alarm.json
- JSON/Colored Switches.json
- JSON/Microcontroller.json
- JSON/The Code.json
I thought I've resolved it but apparently I didn't
Resolves request https://discordapp.com/channels/160061833166716928/612414629179817985/697870579767705680
> Symbols Update VIII - Removed duplicates

- HTML/Bamboozling Time Keeper condensed (Fang).html
Bamboozling Time Keeper Nerfs Update - while also updated condensed manual in order to compensate with the changes to the original manual.
Updated PDFs are missing - either after I get my new laptop and print it (after 1-3 days) or maintainer to reprint the two manuals (sorry for inconvenience!)
> NERFS. (according to author)

- More/Logfile Analyzer.js
Create a separate array that indexes the fields that getModuleData() is referencing, so it need not iterate over the entirety of parseData every single time. This was the single biggest bottleneck I could find by profiling the LFA while it analyzed a large log file, and making this changed dropped the load time for a ~6mb log file from almost two minutes, to about five seconds.
> Index parseData before access

- HTML/Iconic interactive (Kaito Sinclaire).html
> Iconic interactive: Chromium-based browser support

- HTML/Faulty RGB Maze interactive (Andrio Celos).html
This commit adds the newly changed fault 8 to the template.
> Faulty RGB Maze interactive update

- HTML/Bamboozling Button Grid optimized (Fang).html
- HTML/Bamboozling Button Grid optimized numbers (Fang).html
- HTML/Bamboozling Time Keeper condensed (Fang).html
Another long lasted error fix on bbg opt and minor change to btk cond
> PR 58: Bamopt Update

- HTML/The High Score.html
Swap rules C and W to resolve an extremely rare infinite loop.
> The High Score manual update

- HTML/Sorting.html
Holy crap this took so long because of many dumbos.
> This time sorting update for real.

- JSON/100 Levels of Defusal.json
- JSON/7.json
- JSON/Accelerando.json
- JSON/Audio Morse.json
- JSON/Badugi.json
- JSON/Blind Arrows.json
- JSON/Brawler Database.json
- JSON/Caesar’s Maths.json
- JSON/Elder Password.json
- JSON/Factoring.json
- JSON/Identifying Soulless.json
- JSON/Juxtacolored Squares.json
- JSON/Malfunctions.json
- JSON/Name Changer.json
- JSON/Negativity.json
- JSON/Pickup Identification.json
- JSON/Pixel Cipher.json
- JSON/Remote Math.json
- JSON/Roger.json
- JSON/Shifted Maze.json
- JSON/Simon’s Ultimate Showdown.json
- JSON/Spangled Stars.json
- JSON/Stars.json
- JSON/Switching Maze.json
- JSON/Tetriamonds.json
Evaluated a bunch of unconsidered modules for souv support. First time using Git so lemme know if I break everything.
> Souvenir Evalutions Part I

- JSON/Push The Button.json
The module sometimes gives strikes when inputting a correct digit.
> Marked Push the Button as unplayable.

- HTML/Tech Support.html
- JSON/Tech Support.json
Shortened the original description and added tags.
> Updated module description Tech Support

- More/FAQs.html
Add 42 and 501, remove Everything
> Update Boss list in FAQ

- HTML/The Arena.html
> Update The Arena.html

- HTML/101 Dalmatians translated (日本語 — 101匹ワンちゃん) (tepel).html
- HTML/15 Mystic Lights translated (日本語 — 15の神秘の光) (tepel).html
- HTML/1D Maze translated (日本語 — 1D迷路) (tepel).html
- HTML/21 translated (日本語 — 21) (tepel).html
- HTML/3D Maze translated (日本語 — 3D迷路) (tepel).html
- HTML/Adjacent Letters translated (日本語 — 隣接アルファベット) (tepel).html
- HTML/Alphabet translated (日本語 — アルファベット) (tepel).html
- HTML/Binary LEDs translated (日本語 — 二進法LED) (tepel).html
- HTML/Caesar Cipher translated (日本語 — カエサル暗号) (tepel).html
- HTML/Colour Flash translated (日本語 — カラーフラッシュ) (tepel).html
- HTML/Connection Check translated (日本語 — 接続確認) (tepel).html
- HTML/Digital Root translated (日本語 — 数字根) (tepel).html
- HTML/Emoji Math translated (日本語 — 絵文字算) (tepel).html
- HTML/Forget It Not translated (日本語 — 其忘る勿かれ) (tepel).html
- HTML/Forget Me Not translated (日本語 — 我忘る勿かれ) (tepel).html
- HTML/Kanji translated (日本語 — 漢字) (tepel).html
- HTML/Letter Keys translated (日本語 — 文字キー) (tepel).html
- HTML/Lights Out translated (日本語 — ライツアウト) (tepel).html
- HTML/Morse Code translated (日本語 — モールス信号).html
- HTML/Password translated (日本語 — パスワード).html
- HTML/Switches translated (日本語 — スイッチ) (tepel).html
- HTML/The Button translated (日本語 — ボタン).html
- HTML/Who’s on First translated (日本語 — 単語パズル).html
- HTML/Wire Placement translated (日本語 — 配置ワイヤ) (tepel).html
- HTML/Word Search translated (日本語 — ワードサーチ) (tepel).html
- HTML/Yahtzee translated (日本語 — ヤッツィー) (tepel).html
- HTML/css/font-japanese.css
> Use common css file for fonts in Japanese manual

- HTML/Not Memory.html
See https://github.com/AndrioCelos/KtaneNotVanillaModules/commit/3233a7b46c88932ee69c319c679e82eeb1f6917c for more information.
> Not Memory rule change

- HTML/Commuting.html
A very minor patch to help clarify how this module interacts with Zen Mode.
> [Commuting]Add Zen mode clause to the manual.

- HTML/Table Madness.html
Forgot to mention that you have to add 3 if it's less than 3-5.
> Update Table Madness.html

- HTML/Unicode.html
> Fix typos in Unicode html manual

- HTML/1D Maze translated (Español — Laberinto 1D) (MásQuéÉlite).html
- HTML/Adventure Game translated (Español — Juego de Aventuras) (MásQuéÉlite).html
- HTML/Art Appreciation translated (Español — Aprecicación del Arte) (MásQuéÉlite).html
- HTML/Bitwise Operations translated (Español — Operaciones con bits) (MásQuéÉlite).html
- HTML/Forget Me Not translated (Español — No me olvides) (MásQuéÉlite).html
- HTML/Friendship translated (Español — Amistad) (MásQuéÉlite).html
- HTML/Turn The Key translated (Español — Gira la llave) (MásQuéÉlite).html
> More tweaks + 2 translations (es)

- HTML/Forget Maze Not.html
Added some clarification and update blue rule.
> Update FMzN Manual

- HTML/Symbolic Tasha.html
Request from https://discord.com/channels/160061833166716928/612414629179817985/779529151887441950
> Fix Symbolic Tasha tables position

- HTML/Another Keypad Module.html
Request from https://discord.com/channels/160061833166716928/612414629179817985/781032629382283264
> Another Keypad Module: increase font size

- JSON/Entry Number Four.json
https://discord.com/channels/160061833166716928/612414629179817985/790198396891168768
> Change EntryNumberFour's expert difficulty

- HTML/The Duck.html
https://discord.com/channels/160061833166716928/612414629179817985/790340940022939648
> The Duck manual update

- HTML/hexOS.html
https://discord.com/channels/160061833166716928/612414629179817985/789461203755204618
> Add note to hexOS

- HTML/Brown Bricks reworded (Rdzanu).html
https://discord.com/channels/160061833166716928/612414629179817985/792351165433905153 
Lower the images so the first html page fits on one pdf page
> Resize Brown Bricks reworded images

- JSON/Simon Subdivides.json
https://discord.com/channels/160061833166716928/612414629179817985/792506296439013387
> Add Simon Subdivides video tutorial

- HTML/Linq.html
https://discord.com/channels/160061833166716928/612414629179817985/792533421024083978
> Update Linq manual

- HTML/Guess Who.html
https://discord.com/channels/160061833166716928/612414629179817985/792808316387590145
> Update Guess Who manual

- More/Logfile Analyzer.js
Request from tepel https://discord.com/channels/160061833166716928/612414629179817985/782315510699917323
> Fix manual link for needies

- More/Logfile Analyzer.js
- More/TDSBombRenderer/TDSBombRenderer.js
Did these from my phone ;-;
Hopefully this will work, I just want to get something out that fixes these 2 issues before I have time to make all of the big changes
> LFA Bomb Renderer mobile hotfixes

- More/Logfile Analyzer.js
- More/TDSBombRenderer/TDSBombRenderer.js
Realized I accidentally left this in when looking at the console on the LFA. That's a lot of logs...
> Remove bomb renderer debug logging

- HTML/Echolocation.html
- HTML/Fractal Maze.html
- HTML/Micro-Modules.html
- HTML/Musical Transposition.html
- HTML/NOT NOT.html
- HTML/Simon Screams condensed (samfundev).html
- JSON/Updog.json
New manuals for Fractal Maze and NOT NOT
Minor change to the Simon screams condensed
Updated the Updog json
Updated the micro-mods manual
Updated the Musical Transposition manual
Updated the echolocation manual
> Manual and json updates

- HTML/Word Search.html
This is my first pull request for this repo, let me know if there is another procedure I should be aware of. This change makes highlighting work on the Word Search.html manual.
> Added highlighting to Word Search manual

- HTML/Addition translated (Español — Sumas) (MásQuéÉlite).html
I Finally managed to get GitHub working as I wanted QwQ. Cheers for MQE(?)
> Spanish Translation (Addition)

- HTML/Algebra translated (Русский — Алгебра) (PoisonGreen).html
- HTML/Cooking translated (Русский — Готовка) (PoisonGreen).html
- HTML/Green Arrows translated (Русский — Зелёные Стрелки) (PoisonGreen).html
- HTML/Juxtacolored Squares translated (Русский — Смежные цветные квадраты) (PoisonGreen).html
- HTML/Orange Arrows translated (Русский — Оранжевые Стрелки) (PoisonGreen).html
- HTML/Purple Arrows translated (Русский — Фиолетовые Стрелки) (PoisonGreen).html
- HTML/Red Arrows translated (Русский — Красные Стрелки) (PoisonGreen).html
- HTML/Shape Shift translated (Русский — Изменение формы) (PoisonGreen).html
- HTML/Yellow Arrows translated (Русский — Жёлтые Стрелки) (PoisonGreen).html
Fixed Shape Shift manual (flat-flat had a typo, round-round had a weird sentence and included cyrillic css file)
Added translated manuals for: Algebra, Cooking, Green Arrows, Juxtacolored Squares, Orange Arrows, Purple Arrows, Red Arrows, Yellow Arrows.
> Russian translated manuals

- HTML/Mislocation interactive (Darksly).html
Added Rectangle Multi-selection (Shift-Arrows) 
- Selects the rectangle shape between two cells
> [Mislocation] [Interactive Manual] Added Rectangle Multi-selection

- JSON/Cruel Garfield Kart.json
- JSON/Double Pitch.json
- JSON/Emotiguy Identification.json
- JSON/English Entries.json
- JSON/Telepathy.json
- JSON/The Calculator.json
- JSON/The Kanye Encounter.json
- JSON/The Overflow.json
Updated contributors to the following modules:
English Entries, The Calculator, The Kanye Encounter, Telepathy, Emotiguy Identification
Updated souvenir compatibility to the following modules:
The Overflow, Telepathy, Double Pitch, Cruel Garfield Kart
> Several JSON updates

- HTML/Forget Maze Not interactive (Darksly).html
- Tweaked **Red maze** to a pressable grid 
- Added **coordinates** to red maze cells
- Added **Shift + Tab** Command (Got to the cell directly below)
- Changed default value of arrow behavior to _**Toggle borders**_
> [Forget Maze Not] Tweaked Interactive Manual and added some new features

- HTML/Cell Lab.html
- HTML/Digisibility.html
- HTML/Pandemonium Cipher.html
- JSON/Cell Lab.json
- JSON/Kugelblitz.json
- **Pandemonium Cipher:** Changed two paragraphs in the Manual
- **Digisibility:** Changed a paragraph in the Manual
- **Kugelblitz:** Fixed JSON tagging
-  **Cell Lab:** Changed a paragraph in the manual and the description
> [General] Manuals and JSON tweaks

- JSON/3 LEDs.json
- JSON/Boomdas.json
- JSON/Frankenstein's Indicator.json
**Modules are:**
- 3 LEDs
- Boomdas
- Frankenstein's Indicator
> [General] Added new tutorial videos for 3 different modules

- JSON/OmegaDestroyer.json
- More/Logfile Analyzer.js
**[Logfile Analyzer]** Removed Holdables on the logfile module list until it makes sence to put them back. 
Also fixed a small mistake on the javascript causing the webconsole to report an error.
**[OmegaDestroyer]** Fixed wrong link for video tutorial
> [General] Fixed holdable showing on logfile / Fixed wrong tutorial link

- HTML/Golf.html
- HTML/The Speaker.html
- JSON/Interpunct.json
Updated The Speaker
Updated Golf
Updated Interpunct
> Minor updates

- HTML/Numerical Knight Movement.html
Added a small credit note to Pruz module as requested;
Fixed unproportional image styles;
> [Numerical Knight Movement] Added a credit note and fixed image

- More/Logfile Analyzer Data.js
- More/Logfile Analyzer.css
- More/Logfile Analyzer.js
Code to support the new [Logfile Bomb Preview](http://steamcommunity.com/sharedfiles/filedetails/?id=2397444702) mod.
> Add Logfile Bomb Preview support

- HTML/ASCII Maze interactive (tepel).html
* Clicking cell will no longer move the icons.
* Added instructions
* Added alternative table mode
> Update ASCII Maze iteractive manual

- HTML/Echolocation interactive (tepel).html
* Changed to 4x4 maze
* Added instructions
* Shifting walls don't delete when it is off the edge
* Interactive part is smaller and easier to see
* Left click doesn't move icons anymore
> Update Echolocation interactive

- HTML/A-maze-ing Buttons.html
- HTML/AAAAA.html
- HTML/Alphabetical Ruling.html
- HTML/Bartending.html
- HTML/Basic Morse.html
- HTML/Busy Beaver.html
- HTML/Colour Code.html
- HTML/Drive-In Window.html
- HTML/Encrypted Values.html
- HTML/Indigo Cipher.html
- HTML/Jaden Smith Talk.html
- HTML/Lyrical Nonsense.html
- HTML/Maintenance.html
- HTML/Not Simaze.html
- HTML/Repo Selector.html
- HTML/The iPhone.html
- HTML/Ultimate Custom Night.html
Finished:
AAAAA: page 1 blank
Alphabetical Ruling: table leak
Bartending: table leak
Basic Morse: image leak
Busy Beaver: page 3 blank
Colour Code: table leak
Drive-In Window: table leak
Encrypted Values: table leak
Indigo Cipher: table leak
The iPhone: table leak
Jaden Smith Talk: list leak
A-maze-ing Buttons: image leak
Lyrical Nonsense: table leak
Maintenance: table leak
Not Simaze: table leak
Orange Cipher: paragraph/list leak
Repo Selector: paragraph/list leak
Ultimate Custom Night: list leak
> Fix PDF leaks and blank pages

- HTML/Letter Grid.html
General clarifications and removal of extraneous information.
> Fixes with Letter Grid manual

- JSON/Mystery Widget.json
Change from Problematic to Incompatible
> Oops, put wrong compatibility tag on Mystery Widget

- HTML/Letter Grid.html
I need to find out how to test PRs before creating them
> Hopefully final fix to letter grid

- ContactInfo.json
This time without deleting half of Timwi's info.
> Add contact info for S.

- HTML/IKEA interactive (LuminoscityTim).html
- HTML/Not Maze interactive (LuminoscityTim).html
- HTML/img/IKEA/mazeA_rot.svg
- HTML/img/IKEA/mazeB_rot.svg
- HTML/img/IKEA/mazeC_rot.svg
- HTML/img/IKEA/mazeD_rot.svg
- HTML/img/IKEA/mazeE_rot.svg
- HTML/img/IKEA/mazeStart.svg
- HTML/img/IKEA/mazeStop.svg
Added manual for IKEA where you can rotate the mazes.
> Added IKEA interactive manual

- HTML/Not Who's on First.html
- HTML/Not the Button.html
This pull request merges changes to the Not Vanilla Modules manual.
> Not Vanilla manual changes

- JSON/Shifting Maze.json
> Mark Shifting Maze as compatible

- HTML/IKEA interactive (LuminoscityTim).html
- HTML/Know Your Way.html
- HTML/The Number.html
Added line-by-line highlighting to The Number
Added line-by-line highlighting to Know Your Way manual
Minor typo and clarification on IKEA interactive
All HTML files were linted with LogBot
> Added line-by-line highlighting to The Number and Know Your Way, typo on IKEA interactive

- HTML/Art Appreciation translated (Español — Apreciación del Arte) (MásQuéÉlite).html
- HTML/Bitwise Operations translated (Español — Operaciones con bits) (MásQuéÉlite).html
> Fix ES manuals

- HTML/Maze³ interactive (LuminoscityTim).html
- HTML/Maze³.html
- HTML/Word Search translated (Español — Sopa de Letras).html
- HTML/Word Search translated (Français — Mot Mellé).html
- HTML/Word Search translated (Polski — Wykreślanka).html
- HTML/Word Search translated (Čeština — Osmisměrka).html
- HTML/Word Search translated (Русский — Поиск слова).html
- HTML/Word Search translated (日本語 — ワードサーチ) (tepel).html
- HTML/Word Search translated (简体中文 — 拼字游戏).html
- HTML/Word Search translated (繁體中文 — 查字遊戲).html
- HTML/Word Search.html
Added highlighting to Maze cubed and added Maze cubed interactive.
Fixed highlighting hit boxes and linting errors on all Word Search manual versions.
All files were linted with LogBot, the only error is the Special Elite error, but that font does exist and does render properly with the rest of the repo files present.
> Added highlighting to Maze-cubed and fixed Word Search highlighting hit boxes

- HTML/Adventure Game translated (Español — Juego de Aventuras) (MásQuéÉlite).html
- HTML/Art Appreciation translated (Español — Apreciación del Arte) (MásQuéÉlite).html
- HTML/Bitwise Operations translated (Español — Operaciones con bits) (MásQuéÉlite).html
- HTML/Black Hole translated (Español — Agujero negro) (MásQuéÉlite).html
- HTML/Chess translated (Español — Ajedrez) (MásQuéÉlite).html
- HTML/Friendship translated (Español — Amistad) (MásQuéÉlite).html
After 2h I finally managed to create this Pr successfully :3
> Fix ES manuals + transl. Black Hole

- HTML/Hinges.html
I was given permission by the author
https://discord.com/channels/160061833166716928/640556416247267358/831651656584265778
> Made Hinges manual more clear

- HTML/Boolean Venn Diagram lookup table (Katarina).html
Fixes several wrong entries in the lookup table for BVD.
> Boolean Venn Diagram lookup table fixes

- More/FAQs.html
- Add profile bomb
- Add voice bomb
- Update pseudo-needy, boss, and manual challenge lists.
> May FAQ Update

- More/Logfile Analyzer Data.js
This HAS been tested thoroughly.
> Add 2048 LFA

- HTML/Deck Creating.html
- JSON/Coverage.json
- Coverage is a needy, not a regular module
- Deck Creating wording change + card changes (mainly in amount + a typo)
> Coverage JSON change; Deck Creating manual change.

- HTML/Morse-A-Maze.html
Changed greater than 18 to greater than 17.
> Fixed a typo

- HTML/Hitman.html
Without a cycle command, the module expected different names than what was in the manual. 
Parenthesis added to show the differences from what the module expects vs. what the manual has for reference.
> Fixed TP Impossible cases

- HTML/Bamboozling Button optimized (Fang).html
- HTML/Maritime Flags.html
- HTML/Multicolored Switches.html
- HTML/Shape Shift translated (Polski — Zmiana Kształtu).html
- HTML/Shape Shift translated (Čeština — Změna Tvaru).html
- HTML/Shape Shift translated (Русский — Изменение формы).html
- HTML/Shape Shift.html
- HTML/Tasha Squeals optimized (Timwi).html
- HTML/Tasha Squeals.html
- HTML/The Stare.html
- HTML/css/main.css
* Make background color for SVGs white
* Make background color for pages black so that they don't leave white bars
* Changed color for link from blue to orange 
* Fixed Bamboozling Button optimized manual's white cell
* Fixed Maritime Flag bearing 
* Fixed Shape shift diagram
* Fixed Tasha Sequeals cell in table
* Fixed The Stare custom background
> Some dark mode fixes

- HTML/101 Dalmatians translated (Русский — 101 Далматин) (Enoral).html
- HTML/15 Mystic Lights translated (Русский — 15 Загадочных Огней) (Enoral).html
- HTML/Accumulation translated (Русский - Накопление) (Enoral).html
- HTML/Lights Out translated (Русский — Гасите Свет) (Enoral).html
- HTML/❖ translated (Русский — ❖) со словами от Espik (Enoral).html
- HTML/❖ translated (Русский — ❖) со словами от Limeboy (Enoral).html
Added a translated manual for Accumulation and also fixed Cyrilic fonts in my other manuals.
> Okay. Seriously. This is the final request from me for today.

- More/Logfile Analyzer Data.js
This PR improves LFA logging for Repo Selector. Let me know if there is anything I missed, or any formatting mistakes.
> Improve Repo Selector logging

- HTML/NeeDeez Nuts translated (Español — NeeDeez Nuts) (MásQuéÉlite).html
- HTML/egg translated (Español — huevo) (MásQuéÉlite).html
- HTML/egg translated (Español — huevo) simplificado (MásQuéÉlite).html
> Translated some joke manuals into Spanish

- HTML/Quadruple Simpleton.html
- JSON/Quadruple Simpleton.json
> Quadruple Simpleton

- HTML/Mazematics interactive (MásQuéÉlite).html
- More/Logfile Analyzer Data.js
> LFA support for Mazematics and also I fixed Mazematics's log coz it's broken lol

- HTML/Brown's Shadow.html
- HTML/Tech Support reworded (IHateLife).html
- HTML/Tech Support.html
HTMLified.
Maintained the author's style as much as possible.
> Tech support reworded by IHateLife + Tech Support lint

- HTML/14 altered (Fang & Warwick).html
- HTML/14 altered embellished (Quinn Wuest).html
- HTML/14 interactive (MásQuéÉlite).html
- HTML/Curriculum.html
> 14 interactive

- More/Logfile Analyzer Data.js
i did something with that, yay
> Color grid custom LFA

- HTML/Insanagrams lookup table (Qkrisi).html
- HTML/Snack Attack.html
oop finally did it :star_struck:
> Snack attack cursed table thingie & Insanagrams lookup table updated

- HTML/Quadruple Simpleton.html
- JSON/Quadruple Simpleton.json
> Quadruple Simpleton corresponding repository changes

- HTML/Discolored Squares interactive (MásQuéÉlite).html
> Discolored Squares interactive

- HTML/Morsematics translated (Español — Morsemáticas) (MásQuéÉlite).html
- HTML/Morsematics translated (Français — Mathémorse) (nekmao33).html
- HTML/Morsematics translated (Português — Morsemática) (Darksly).html
- HTML/Morsematics translated (Čeština — Matematická Morseovka).html
- HTML/Morsematics translated (Русский — Морзематика).html
- HTML/Morsematics translated (日本語 — モールスマティック) (tchen).html
- HTML/Morsematics.html
- HTML/Tetramorse.html
- HTML/The Hexabutton.html
There are so many duplicate morse code charts... omg
> Tetramorse appendix MORSE + dark mode fixes on some morse code charts

- HTML/Complicated Buttons translated (日本語 — 複雑ボタン) (MaximumCombo).html
- HTML/Crazy Talk translated (日本語 — クレイジートーク) 日本語版 (MaximumCombo & hatosable).html
- HTML/Creation translated (日本語 — クリエーション) (MaximumCombo).html
- HTML/English Test translated (日本語 — 英語検定) (MaximumCombo).html
- HTML/Mastermind Cruel translated (日本語 — 残酷マスターマインド) (MaximumCombo).html
--Complicated button
--Creation
--English Test
--Mastermind Cruel
--Crazy Talk (Japanese Edition)
> Added Japanese Manuals

- HTML/Chess interactive (samfundev).html
Compared to the normal manual, I added the `updateChessboardLabels` function in case the rule seed is modified manually. There might be a better to update the chessboard, as I am not very familiar with javascript.
> Add rule seed to Chess interactive

- HTML/Crazy Talk translated (Deutsch — Verrücktes Geschwätz) übersetzt (BerniNotFound).html
Thanks BerniNotFound for working on this!
> Added German Manual for Translated Crazy Talk

- ContactInfo.json
- HTML/Basegate.html
Request: https://discord.com/channels/160061833166716928/612414629179817985/1082672044942033006
Discussion: https://discord.com/channels/160061833166716928/640557658482540564/1111100279857893436
As for the dark mode changes, I changed the first table's centre square colour to contrast more with the dark mode text colour, and made the tables in the switches section adjust for dark mode.
> Basegate changes

- HTML/Blackjack condensed (IHateLife).html
- HTML/Blackjack translated (日本語 — ブラックジャック) 簡略化 (IHateLife, alpha8404).html
Request: https://discord.com/channels/160061833166716928/612414629179817985/1104411663286931456
Permission: https://discord.com/channels/160061833166716928/640557658482540564/1110967943757570208
Made the correction in both the English and Japanese manuals.
> Correct the unicorn in BlackJack condensed manuals.

- HTML/ƎNA Cipher Dream BBQ Alternative.html
- HTML/ƎNA Cipher.html
- JSON/Base Off.json
- JSON/Matrices.json
Request: https://discord.com/channels/160061833166716928/612414629179817985/1111275641480949820
Tutorials have been redone by the same person, so they replace the old ones.
> Update tutorial links for base off and matrices

- HTML/Cipher Machine Portax.html
Request: https://discord.com/channels/160061833166716928/612414629179817985/1111672918141845524
Also did a little bit of formatting (cutting line lengths).
> Update Cipher Machine Portax.html

- JSON/Actions and Consequences.json
Request: https://discord.com/channels/160061833166716928/612414629179817985/1112036636788793424
> Update Actions and Consequences.json

- HTML/Johnson Solids alternate (PANOPTES).html
- HTML/Johnson Solids combined (Hawker).html
- HTML/Johnson Solids.html
Cleaned it up as much as possible, hopefully I didn't miss anything
> Johnson solids combined manual and typo fix

- HTML/Blank Slate.html
* add missing info
* prevent text getting in the way of highlighting in colourblind diagram
> Blank Slate manual update

- HTML/Poker translated (日本語 — ポーカー) (hatosable).html
- HTML/Poker.html
Credit also to Kuro, and apologies for the failed pr earlier: I had a severe lapse of judgement.
> SVGify Poker and Poker (JP Translation) flowcharts

- More/Logfile Analyzer Data.js
- More/Logfile Analyzer Styling Data.css
Reordering refers to reordering the LFA support for modules near the bottom of the Logfile Analyzer Data.js file.
> Walking cube LFA and reordering

- More/Logfile Analyzer Data.js
- More/Logfile Analyzer Styling Data.css
Also simplify Walking Cube LFA
> Add LFA support to Connect Four

- More/Logfile Analyzer Data.js
- More/Logfile Analyzer Styling Data.css
Revised Shoddy Chess lfa so it uses svgs to display graphics rather than text. Took inspiration from interactive manual.
> Updated Shoddy Chess LFA

- HTML/Wire Testing.html
> Update Wire Testing.html

- HTML/FizzBoss.html
- HTML/Overcooked.html
- HTML/Wire Testing.html
Did some wording fixes thanks to @rosenothorns03
> Overcooked/FizzBoss/Wire Testing Manual updates

- More/Logfile Analyzer Data.js
- More/Logfile Analyzer Styling Data.css
Changed logging so it resembles manual graphics
> Logical Hexabuttons LFA support

- More/Logfile Analyzer Data.js
Kuro, I **Guarantee** you will not find anything here :)
> Add btk lfa support

- More/Logfile Analyzer Styling Data.css
The teamwork was real with this one. My game files' integrity is so verified right now.
> Add css styling to Pattern Cube LFA

- More/Logfile Analyzer Data.js
- More/Logfile Analyzer Styling Data.css
* Added Puzzle Pandemonium LFA support
* Fixed Match 'em and Cruel Match 'em LFA support in addition to refactoring code to use jQuery
> LFA additions and fixes

- HTML/The Octadecayotton.html
Emik, I may return at a later date to code this manual better! :3
> Fix grammar error

- More/Logfile Analyzer Data.js
- More/Logfile Analyzer Styling Data.css
Updated the LFA for Langton’s Anteater so it resembles the interactive.
NOTE: There is a [bug](https://discord.com/channels/160061833166716928/640556416247267358/1131738499767357490) with the logging that affects the LFA, however, the log within the LFA is correct.
> Langton’s Anteater LFA

- More/Logfile Analyzer Data.js
- More/Logfile Analyzer Styling Data.css
* Added LFA support for Mystic Square and Echolocation.
* Didn't actually do an awful lot else this time round for a change
* bullet point 3
> Add LFA supports

- ContactInfo.json
- JSON/Countdown.json
- JSON/Cruel Countdown.json
- JSON/Free Parking.json
- JSON/Memorable Buttons.json
- JSON/Risky Wires.json
- JSON/The Matrix.json
Been a while, hasn't it?
Notes every module I can remember offhand that I did TP support for, as well as adds my contact info just in case something breaks. Probably not likely since most of these have been going strong for 3+ years now, but _you never know_...
> Clarifying TP support + contact info

- More/Logfile Analyzer Data.js
- More/Logfile Analyzer Styling Data.css
* Borders!!
* Margins!!
* `const` and `let`!!
* Simplified `value==null` to `!value` !!
> Grid Matching LFA Styling

- More/Logfile Analyzer Data.js
- Sorted stages in chronological order
- Used dropdowns so the extra information about each stage is hidden
[Request](https://discord.com/channels/160061833166716928/1018575584009400350/1133942724245069884)
> Finished Forget Us Not LFA

- More/Logfile Analyzer Data.js
- Converted each stage's information into a dropdown
- The header will show the module name for that stage (`?` if the stage doesn't have a module)
- The content of the dropdown will be what were the displayed LEDs, and the actual LEDs after the broken evaluation
- Converted color evaluation in solving stage into a dropdown
- The header will show the color in its respective LED value
- The content of the drop down will show the multiplier and the occurrence of said color
> Forget Them All LFA

- More/Logfile Analyzer Data.js
Used nest drop downs to make information easier to digest. Example log attached
[Character Slots LFA.txt](https://github.com/Timwi/KtaneContent/files/12178583/Character.Slots.LFA.txt)
[Request](https://discord.com/channels/160061833166716928/1018575584009400350/1133889859812077639)
> Character Slots LFA

- More/Logfile Analyzer Data.js
- More/Logfile Analyzer Styling Data.css
Converted all lines about each suspect into an svg of the mansion
[Request](https://discord.com/channels/160061833166716928/1018575584009400350/1133926468922122271)
> Not murder LFA

- More/Logfile Analyzer Data.js
- Added drop down for current cell description
> Scrutiny Squares LFA

- More/Logfile Analyzer Data.js
Made the lines that tell you the cost of items to resemble a menu
> Drive In Window LFA

- HTML/Run-On Sentence.html
Fix page boundaries and improve centering
> Update Run-On Sentence

- HTML/Activities reordered (Hawker).html
Reorganized the table so that they are alphabetical order
[Request](https://discord.com/channels/160061833166716928/612414629179817985/1135001101305905202)
> Activities Reorganized

- More/Logfile Analyzer Data.js
> Add catch-all regex

- More/Logfile Analyzer Data.js
- More/Logfile Analyzer Styling Data.css
Also simplify comparisons to `null`.
> Add dark mode to X-ray LFA

- HTML/Intensity Levels translated (Čeština — Stupně Intenzity) (Cirax856 & Asmir).html
> Fixed small typo in Intensity Levels Czech translation

- HTML/Function Identification translated (Čeština — Identifikace Funkcí) (Cirax856 & Asmir).html
> Fixed small typo in Function Identification Czech translation

- HTML/Ultimate Team.html
The manual has been updated to adapt to the major change made to the repo.
> Ultimate Team Update

- HTML/Blind Alley translated (Čeština — Slepá Ulička) (Frank, Cirax856, adamcz).html
- HTML/Chord Qualities translated (Čeština — Vlastnosti Akordů) (Frank & adamcz).html
- HTML/Follow the Leader translated (Čeština — Následuj Vůdce) (Frank & adamcz).html
- HTML/Modules Against Humanity translated (Čeština — Moduly Proti Lidskosti) (Frank & adamcz).html
- HTML/Monsplode, Fight! translated (Čeština — Monsplode, Bojuj!) (Frank & adamcz).html
- HTML/Point of Order translated (Čeština — Další v Pořadí) (Frank & adamcz).html
Frank (the Czech translator) has made a lot of changes to Czech translated manuals. Since he doesn't have much experience with GitHub and does not want to upload them one by one in #repo-requests, he asked me to upload them for him.
> Frank translation updates

- More/Logfile Analyzer Data.js
- More/Logfile Analyzer Styling Data.css
Added visuals to the grid layout along of a valid path
> Papyrus Tiles LFA

- HTML/Skewed Slots translated (한국어 — 스큐 슬롯) (Zye).html
- HTML/Square Button translated (한국어 — 사각 버튼) (Zye).html
- HTML/Switches translated (한국어 — 스위치) (Zye).html
- HTML/Symbolic Password translated (한국어 — 심볼 비밀번호) (Zye).html
- HTML/Text Field translated (Español — Campo de carácteres) (MásQuéÉlite).html
- HTML/Text Field translated (Français — Champ de Texte) (noi2coco).html
- HTML/Text Field translated (Polski — Pole Tekstowe).html
- HTML/Text Field translated (Čeština — Textové Pole) (Frank & adamcz).html
- HTML/Text Field translated (Русский — Поле из букв).html
- HTML/Text Field translated (日本語 — テキストフィールド) (tchen).html
- HTML/Text Field translated (繁體中文 — 文字領域).html
- HTML/Text Field translated (한국어 — 텍스트 필드) (Zye).html
- HTML/Text Field.html
- HTML/css/Modules/Text Field.css
Translated following modules in Korean:
Skewed Slots, Square Button, Switches, Symbolic Password, Text Field
> Korean manuals for Skewed Slots ~ Text Field

- HTML/Blind Alley translated (Čeština — Slepá Ulička) (Frank, Cirax856, adamcz).html
Added the BLANK Appendix to the Czech translation of the Blind Alley Manual.
> Updated Blind Alley Czech translation

- HTML/Captain Wheeler.html
Added wheel speed reference table
> Added clarification for Captain Wheeler

- HTML/Bicolored Squares translated (한국어 — 이색 사각형들) (Zye).html
- HTML/Colored Squares translated (한국어 — 색 사각형들) (Zye).html
- HTML/Decolored Squares translated (Français — Carrés Dépigmentés) (noi2coco).html
- HTML/Decolored Squares translated (Português — Quadrados Pigmentados) (DarkSly).html
- HTML/Decolored Squares translated (Русский — Обесцвеченные квадраты).html
- HTML/Decolored Squares translated (日本語 — 色抜き格子) (tchen).html
- HTML/Decolored Squares translated (繁體中文 — 掉色方格) (Snow Note).html
- HTML/Decolored Squares translated (한국어 — 탈색 사각형들) (Zye).html
- HTML/Decolored Squares.html
- HTML/Discolored Squares embellished (Qkrisi).html
- HTML/Discolored Squares interactive (MásQuéÉlite).html
- HTML/Discolored Squares translated (Français — Carrés Décolorés) (noi2coco).html
- HTML/Discolored Squares translated (Português — Quadrados Tingidos) (DarkSly).html
- HTML/Discolored Squares translated (Русский — Бесцветные квадраты).html
- HTML/Discolored Squares translated (日本語 — 色変え格子) (tchen).html
- HTML/Discolored Squares translated (日本語 — 色変え格子) インタラクティブ (MásQuéÉlite, alpha8404).html
- HTML/Discolored Squares translated (繁體中文 — 變色方塊) (Snow Note).html
- HTML/Discolored Squares translated (한국어 — 변색 사각형들) (Zye).html
- HTML/Discolored Squares.html
- HTML/Isocolored Squares translated (한국어 — 등색 사각형들) (Zye).html
- HTML/Juxtacolored Squares translated (한국어 — 각색 사각형들) (Zye).html
- HTML/css/Modules/Decolored Squares.css
- HTML/css/Modules/Discolored Squares.css
Korean manuals for:
- Bicolored, Decolored, Discolored, Isocolored, Juxtacolored squares
Edited Colored Squares Korean manual
Cleaned Discolored Squares CSS
> Korean Manuals for some Colored Square modules

- HTML/Brown Bricks reworded (Rdzanu).html
- JSON/Divisible Numbers.json
- JSON/Logic Statement.json
- JSON/Reverse Polish Notation.json
- Remove some commas in Brown Bricks (reworded)
- Update Divisible Numbers JSON
- Update Logic Statement JSON
- Update Reverse Polish Notation JSON
> Minor changes

- HTML/Souvenir.html
- JSON/Book of Mario.json
- JSON/Flavor Text EX.json
- JSON/Flavor Text.json
``` html
<div class="module"><div class="name">Book of Mario</div><ul class="questions"><li>Who said something in each stage?</li><li>What was each character's quote?</li></ul></div>
<div class="module"><div class="name">Flavor Text</div><ul class="questions"><li>Which module's flavor text was presented?</li></ul></div>
<div class="module"><div class="name">Flavor Text EX</div><ul class="questions"><li>Which module's flavor text was presented in each stage?</li></ul></div>
```
> Added souv for Book of Mario, Flavor Text EX, Flavor Text

- More/Logfile Analyzer Data.js
- Converts coordinates of robots into battleship's, with A1 being the red goal
- Grouped movement for the same bot in the same attempt (before strike or reset)
> robot programming LFA

- HTML/Hiragana.html
- HTML/Katakana.html
- JSON/Hiragana.json
- JSON/Katakana.json
The keyboard capture bug has been squashed.
This PR also includes a generic manual update.
Thanks in advance!
> Kana Manual & JSON updates

- More/Logfile Analyzer Data.js
[Logs.zip](https://github.com/Timwi/KtaneContent/files/12922991/Logs.zip)
> The Arena LFA

- More/Logfile Analyzer Data.js
There are no solve/strike messages, so any log will work
> Added 4 buttons LFA

- HTML/Refill that Beer! translated (Polski — Uzupełnij to Piwo!) (Rdzanu).html
- HTML/Turn The Keys translated (Polski — Przekręć Klucze) (Rdzanu).html
- JSON/B-Machine.json
- Fix B-Machine typo in JSON
- Add Refill that Beer! translated
- Add Turn the Keys translated
> Fix typo and add translated manuals.

- HTML/Tic Tac Toe optimized (samfundev).html
- HTML/Tic Tac Toe optimized interactive (LuminoscityTim, samfundev).html
- HTML/Tic Tac Toe optimized interactive (LuminoscityTim-samfundev).html
This manual does not support rule seed. Theoretically, it could, but I'm unfamiliar with rule seed as a whole
> Tic Tac Toe manual that merges the interactive and the optimized

- More/Logfile Analyzer Data.js
I would like all the dropdowns to be expanded by default, but unsure how
[Logs.zip](https://github.com/Timwi/KtaneContent/files/13402454/Logs.zip)
> Added LFA support to Technical buttons

- More/Logfile Analyzer Data.js
- More/Logfile Analyzer Styling Data.css
[Logs.zip](https://github.com/Timwi/KtaneContent/files/13404560/Logs.zip)
> Added Dark Mode support

- More/Logfile Analyzer Data.js
[Directional Button LFA.txt](https://github.com/Timwi/KtaneContent/files/13404695/Directional.Button.LFA.txt)
> Added LFA Support for Directional Buttons

- More/Logfile Analyzer Data.js
[Logs.zip](https://github.com/Timwi/KtaneContent/files/13461328/Logs.zip)
> Advanced shapes colors LFA + fixed Adjacent Letter position in js file

- HTML/Iconic interactive (Kaito Sinclaire).html
Re-flow the two boxes to be [stacked vertically](https://github.com/Timwi/KtaneContent/assets/539749/62d583dc-465c-44f7-885e-295e46038468) if there isn't enough room to have the input box on the left side.
> Iconic interactive: Attempt to gracefully handle portrait orientation (mobile devices)

- More/Logfile Analyzer Data.js
- More/Logfile Analyzer Styling Data.css
[Log.zip](https://github.com/Timwi/KtaneContent/files/13532433/Log.zip)
> Bakery LFA

- More/Logfile Analyzer Data.js
- More/Logfile Analyzer Styling Data.css
[Logs.zip](https://github.com/Timwi/KtaneContent/files/13795723/Logs.zip)
> Added Bridges LFA

- HTML/css/dark-theme.css
Must be merged together with https://github.com/Timwi/KtaneWeb/pull/120
> Add main page "Invert" button dark mode CSS

- HTML/Cursor Maze translated (Русский — Лабиринт курсором) (_Play_).html
- HTML/Jackbox.TV translated (Русский — Jackbox.TV) (_Play_).html
- HTML/The Simpleton translated (Русский — Просто кнопка) (_Play_).html
Russian Translations for:
- Cursor Maze
- Jackbox.TV
- The Simpleton
> [RU] Manual Translations

- HTML/The Hypercube translated (Русский — Гиперкуб) (Megum).html
> Hypercube translated (Ru)

- HTML/Batteries translated (Русский — Элементы питания) (Enoral) .html
- HTML/Indicators translated (Русский — Индикаторы) (Enoral).html
- HTML/Ports translated (Русский — Порты) (Enoral).html
Added translated manuals for vanilla widgets
> [RU] Vanilla widget pack

- HTML/TetraVex interactive (Hawker).html
- More/Logfile Analyzer Data.js
Missing save states, but functional overall
> Tetravex Interactive

- HTML/Roger dot pdf (Eltrick & Blananas2).html
- HTML/Roger translated (日本語 — ロジャー) (hatosable).html
- HTML/Roger.html
To synchronize changes between the module and the manual.
> Rgr - Update + PDF (only Blan pull this)

- HTML/21.html
- HTML/Job Application.html
Job Application - small change.
21 - fixed my mistake.
> Job Application and 21 edits

- HTML/The Triangle Button.html
by adding the missing section div
> The Triangle Button: Make manual highlightable

- HTML/Simon's Ultimate Showdown optimized (uku1928).html
float: right isn't as good as I thought
> SUS optimized: fix Stages + Scrambles div interaction

- HTML/Challenge & Contact.html
when the pages are outside of section
> Challenge & Contact: Side-by-side

- HTML/Press X condensed (mathgeniuszach).html
Relevant repo request: https://discord.com/channels/160061833166716928/612414629179817985/1329828517080203284
> Correct Press X columns

- More/QuizData.js
> Emoji Math Quiz

- More/QuizData.js
> Fixed Alphabet quiz to not randomise ordering of numbers

- HTML/The Fan.html
- HTML/css/Modules/The Fan.css
Changed casing of letters in identification table for symbol font to make symbols on The Fan easier to identify.
Corrected page 2's numbering from `page 1 of 2` to `page 2 of 2`.
> Fix identification of symbols and page numbering on The Fan

- HTML/The Colored Fan.html
Fixed wording that was confusing to some players.
> Clarify wording of steps in The Colored Fan

- HTML/The Fan.html
Fix wording and formatting on The Fan.
> Correct The Fan's modulo rule

- HTML/Uncolored Simon.html
Added the number of stages in the last phase to the manual.
> Updated wording in the last phase of the  Uncolored Simon manual.

- HTML/UFO Satellites.html
- Replaced `<i>` with `<span class="example">` and replaced `<em>` with `<b class="lead">`.
> Fixed UFO Satellites html tag formatting

- HTML/4D Tunnels.html
Fix 4D Tunnels mobile display.
Fix 4D Tunnels viewbox issues on lower symbols
> Add alternate view to 4D Tunnels.
